heat_template_version: queens

description: >
  Uses cloud-init to enable root logins and set the root password.
  And set the heat-admin user

parameters:
  NodeRootPassword:
    description: Root password for the nodes
    hidden: true
    type: string

  node_admin_username:
    type: string
    default: heat-admin

  node_admin_extra_ssh_keys:
    type: comma_delimited_list
    default: []

resources:
  userdata:
    type: OS::Heat::MultipartMime
    properties:
      parts:
      - config: {get_resource: root_config}
      - config: {get_resource: user_config}

  root_config:
    type: OS::Heat::CloudConfig
    properties:
      cloud_config:
        ssh_pwauth: true
        disable_root: false
        chpasswd:
          list:
            str_replace:
              template: "root:PASSWORD"
              params:
                PASSWORD: {get_param: NodeRootPassword}
          expire: False

  user_config:
    type: OS::Heat::CloudConfig
    properties:
      cloud_config:
        user: {get_param: node_admin_username}
        ssh_authorized_keys: {get_param: node_admin_extra_ssh_keys}

outputs:
  OS::stack_id:
    value: {get_resource: userdata}



